import gamesData from "../games.json";

export type Game = {
  id: string;
  title: string;
  author: string;
  description: string;
  sourceId: string;
  sourceTitle: string;
  sourcePath: string;
  sourceSubpath?: string;
  sourceEntry?: string;
  sourceUrl: string;
  upstreamUrl: string;
  adapter: string;
  entry: string;
  cover: string;
  coverSource: string | null;
  catalogCoverSource?: string;
  notices: Array<{ target: string; source: string }>;
  license: string;
  edition: string;
  input: string;
  inputs: string[];
  devices: string[];
  session: string;
  category: string;
  group: string;
  language: string;
  quality: string;
  status: string;
  runtime: string;
  tags: string[];
  contentTags: string[];
  technology: string;
  featured: boolean;
  collectionNumber?: number;
};

export const games = gamesData as Game[];
